import Head from 'next/head'
import { useEffect, useState } from 'react'
import api from './api/main'
import { SimpleGrid, Box, Center } from '@chakra-ui/react'
import { Image, Wrap, WrapItem, Container } from '@chakra-ui/react'
import { Text } from '@chakra-ui/react'
import { useToast } from '@chakra-ui/react'
import { Input, InputGroup, Button, InputRightElement, InputLeftAddon, Flex } from '@chakra-ui/react'
import { SearchIcon, SmallCloseIcon } from '@chakra-ui/icons'

export default function Home() {
  const [data, setData] = useState([])
  const [value, setValue] = useState('')
  const [showAll, setShowAll] = useState(false)
  const [offset, setOffSet] = useState(0)
  const toast = useToast()

  useEffect(() => {
    api.get(`/pokemon?limit=12&offset=${offset}`)
      .then(response => setData(response.data.results))
      .catch(err => console.log(err))
  }, [showAll, offset])


  const handleClick = () => {
    api.get(`/pokemon/${value.toLocaleLowerCase()}`)
      .then(response => setData(response.data.species))
      .catch(err => ToastStatusExample())
  };

  const handleClose = () => {
    setValue("")
    setShowAll(!showAll)
  }

  function ToastStatusExample() {
    return (
      <Wrap>
        <WrapItem>
          {toast({
            position: 'top',
            containerStyle: {
              marginTop: 20
            },
            title: 'Pokemon não encontrado',
            status: 'error',
            isClosable: true,
          })}
        </WrapItem>

      </Wrap>
    )
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bg={'#ef5350'} p={'5px'}>
        <Container maxW={['100%', '70%']}>
          <Image src='https://raw.githubusercontent.com/PokeAPI/media/master/logo/pokeapi_256.png' w={120} alt='logo' />
        </Container>
      </Box>
      <Box minHeight={'100vh'} p={5}>
        <Center>
          <Box>
            <Image src='https://raw.githubusercontent.com/PokeAPI/media/master/logo/pokeapi_256.png' alt='logo' margin={10} />
            <InputGroup marginBottom={10} size='md'>
              {value ?
                <InputLeftAddon p={3} bg={'none'}>
                  <SmallCloseIcon onClick={handleClose} />
                </InputLeftAddon>
                : null}
              <Input
                pr='4.5rem'
                type={'text'}
                value={value}
                onChange={(e) => setValue(e.target.value)}
                placeholder='Find your pokemon'
              />
              <InputRightElement width='4.5rem'>
                <Button bg={'#feca1b'} h='1.75rem' size='md' onClick={handleClick}>
                  <SearchIcon />
                </Button>
              </InputRightElement>
            </InputGroup>
          </Box>
        </Center>
        <Center>
          <SimpleGrid columns={{ base: 2, md: 4 }} spacing={[5, 10]}>
            {data.length > 1 ? data.map(item =>
              <Box borderBottom={'8px solid #feca1b'} bg={'#feca1b54'} p={5} borderRadius={10}>
                <Image src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${item?.url?.substr(-3).replaceAll('/', "")}.png`} w={150} cursor='pointer' alt={item?.name} />
                <Text fontSize='2xl' textAlign={'center'}>{item?.name}</Text>
              </Box>
            ) : (
              <Box borderBottom={'8px solid #feca1b'} bg={'#feca1b54'} p={5} borderRadius={10}>
                <Image src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${data?.url?.substr(-3).replaceAll('/', "")}.png`} w={150} cursor='pointer' alt={data?.name} />
                <Text fontSize='2xl' textAlign={'center'}>{data?.name}</Text>
              </Box>
            )}
          </SimpleGrid>
        </Center>
      </Box>
      <Center margin={30}>
        <Box>
          <Text textAlign={'center'}>Page: {offset + 1}</Text>
          <Flex gap={5} marginTop={5}>
            <Button bg={'#feca1b54'} _hover={{ bg: '#feca1b' }} disabled={offset == 0 ? true : false} onClick={(e) => setOffSet(offset - 1)}>Previous</Button>
            <Button bg={'#feca1b54'} _hover={{ bg: '#feca1b' }} onClick={(e) => setOffSet(offset + 1)}>Next</Button>
          </Flex>
        </Box>
      </Center>
      <Box bg={'#ef5350'} textAlign={'center'} p={5} marginTop={50}>
        <Text>Development by: Raphael Caetano</Text>
      </Box>

    </div>
  )
}
